sonar.host.url=http://13.235.134.184:9000
sonar.projectKey=Pipeline:project2
sonar.projectName=Pipeline-project2
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqa_b6b65294a0d969a5beaa4dffe50c80b78c56ce56
