sonar.host.url=http://13.201.70.46:9000
sonar.projectKey=Pipeline:project1
sonar.projectName=Pipeline-project1
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqp_23931114432648b49017f27abada3eef9ed5ae26
