sonar.host.url=http://13.201.17.46:9000
sonar.projectKey=Pipeline:project1
sonar.projectName=Pipeline-project1
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqp_5f15802e2bace5ea871a6dc6261143f506f31fbf
